# Generated by Django 3.0.5 on 2020-04-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200423_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_network',
            field=models.CharField(blank=True, max_length=255, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialidad'),
        ),
    ]
